# Curated API Micronaut Java Library

- https://github.com/sdelamo/curatedapi[Code Repository]
- https://github.com/sdelamo/curatedapi/releases[Releases]
- https://bintray.com/beta/#/groovycalamari/maven/curatedapi[Artifacts]
- https://sdelamo.github.io/curatedapi/api-xref/index.html[Java Docs]

This project is a Java libray to consume the https://curated.co[Curated] API. It is built with https://micronaut.io[Micronaut] and you can use it in a Micronaut app or as a standalone library.

The library exposes methods to consume the endpoints described in the https://curated.co[Curated] API documentation:

- http://support.curated.co/integrations/getting-started-with-the-curated-api/[Getting Curated API]
- http://support.curated.co/integrations/fetching-issue-data-with-the-api/[Fetching Issue data with the API]
- http://support.curated.co/integrations/adding-subscribers-with-the-api/[Adding subscribers with the API]

== Dependency snippet

To use it with https://gradle.org[Gradle]:

[source,groovy]
----
implementation 'groovycalamari.curated:curated:0.0.1'
----

To use it with https://maven.apache.org[Maven]:

[source,xml]
----
<dependency>
<groupId>groovycalamari.curated</groupId>
<artifactId>curated</artifactId>
<version>0.0.1</version>
<type>pom</type>
</dependency>
----


== Configuration

If you want to use the library in Micronaut application, you will need to configure your Curated's publication and api key in the configuration file of your application:

.application.yml
[source,yaml]
----
curated:
  publication-key: 'XXXX'
  api-key: 'YYYY'
----

Once, you have the configuration in place, the library registers a bean of type `CuratedApi` in the Micronaut's application context.

You can use the library without a Micronaut Application Context. In that case, to obtain a `CuratedApi` do:

[source,java]
----
CuratedApi curatedApi = new ManualCuratedApi(new CuratedConfiguration() {
    @Override
    public String getPublicationKey() {
        return "XXXX";
    }

    @Override
    public String getApiKey() {
        return "YYYY";
    }
});
----

== Fetch issues

[source,java]
----
CuratedApi curatedApi;

....

Single<Issues> issues = curatedApi.issues();
----

== Fetch single Issue

[source,java]
----
CuratedApi curatedApi;

....

Single<Issue> issues = curatedApi.issue(1);
----

== Add email subscriber

[source,java]
----
CuratedApi curatedApi;

....

 Single<AddEmailSubscriberResponse> response = curatedApi.addEmailSubscriber(new AddEmailSubscriber("steve@apple.com"));
----

== Build

This library uses https://gradle.org[Gradle]. It uses the plugins:

- https://kordamp.org/kordamp-gradle-plugins/[Kordamp Gradle Plugins]
- https://plugins.gradle.org/plugin/com.gradle.build-scan[Gradle Build Scan Plugins]